CREATE TABLE users (
    id UUID PRIMARY KEY NOT NULL DEFAULT gen_random_uuid(),
    username TEXT NOT NULL UNIQUE CHECK (LENGTH(username) <= 20),
    displayName TEXT NOT NULL CHECK (LENGTH(displayName) <= 20),
    userid INT NOT NULL UNIQUE CHECK (userid > 0),
    email TEXT NOT NULL UNIQUE CHECK (email ~* '^.+@.+\..+$'), 
    password TEXT NOT NULL,
    bio TEXT DEFAULT '',
    followers TEXT[] DEFAULT '{}'::TEXT[],
    following TEXT[] DEFAULT '{}'::TEXT[],
    profilePicture TEXT,
    profileBanner TEXT,
    isbanned BOOLEAN NOT NULL DEFAULT FALSE,
    isOrganisation BOOLEAN NOT NULL DEFAULT FALSE,
    isDeveloper BOOLEAN NOT NULL DEFAULT FALSE,
    isVerified BOOLEAN NOT NULL DEFAULT FALSE,
    isOwner BOOLEAN NOT NULL DEFAULT FALSE,
    ispartner BOOLEAN NOT NULL DEFAULT FALSE,
    isModerator BOOLEAN NOT NULL DEFAULT FALSE,
    isPrivateHearts BOOLEAN NOT NULL DEFAULT FALSE,
    isPrivate BOOLEAN NOT NULL DEFAULT FALSE,
    links TEXT[] DEFAULT '{}'::TEXT[],
    temp_password_expiry TIMESTAMP WITH TIME ZONE DEFAULT NULL CHECK (temp_password_expiry > CURRENT_TIMESTAMP),
    createdat TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP
);